# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2026  Tony Dinh <mibodhi@gmail.com>
#
# Based on (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>

obj-y	:= ix4_200d.o
